spring.application.name=employe_management_system


spring.datasource.username=postgres
spring.datasource.password=Santhosh@17
spring.datasource.url=jdbc:postgresql://localhost:5432/employeesdb

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect